kind: Service
apiVersion: v1
metadata:
  name: stefany-service
spec:
  type: NodePort
  selector:
    app: stefany
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stefany-deployment
  labels:
    app: stefany
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stefany
  template:
    metadata:
      labels:
        app: stefany
    spec:
      containers:
      - name: stefany
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
